// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tars2node(20190529)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "Hello.tars" by Imp Mode
// **********************************************************************

import * as TarsStream from "@tars/stream";
import * as base from "./protocol/Hello";

export namespace Hello {
    export class DemoImp extends base.Hello.DemoImp { 
        public initialize() {
        }

        public testFn(current: base.Hello.DemoImp.testFnCurrent, iLen: number, sName: string, stReq: base.Hello.TestReq, iWidth: number, sFullName: string, stRsp: base.Hello.TestRsp) { 
            stRsp.readFromObject({
                iRet: 0,
                sMsg: "server2 msg"
            })
            setTimeout(()=>{
                current.sendResponse(0, 10, "server2 name", stRsp)
            }, 2000)
        }
    }
}
